// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/fileTransfer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FolderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FolderPath    string                 `protobuf:"bytes,1,opt,name=folder_path,json=folderPath,proto3" json:"folder_path,omitempty"`
	Progress      []*FileProgress        `protobuf:"bytes,2,rep,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FolderRequest) Reset() {
	*x = FolderRequest{}
	mi := &file_proto_fileTransfer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FolderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FolderRequest) ProtoMessage() {}

func (x *FolderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fileTransfer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FolderRequest.ProtoReflect.Descriptor instead.
func (*FolderRequest) Descriptor() ([]byte, []int) {
	return file_proto_fileTransfer_proto_rawDescGZIP(), []int{0}
}

func (x *FolderRequest) GetFolderPath() string {
	if x != nil {
		return x.FolderPath
	}
	return ""
}

func (x *FolderRequest) GetProgress() []*FileProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

type FileProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileProgress) Reset() {
	*x = FileProgress{}
	mi := &file_proto_fileTransfer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileProgress) ProtoMessage() {}

func (x *FileProgress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fileTransfer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileProgress.ProtoReflect.Descriptor instead.
func (*FileProgress) Descriptor() ([]byte, []int) {
	return file_proto_fileTransfer_proto_rawDescGZIP(), []int{1}
}

func (x *FileProgress) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *FileProgress) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Eof           bool                   `protobuf:"varint,4,opt,name=eof,proto3" json:"eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_proto_fileTransfer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fileTransfer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_proto_fileTransfer_proto_rawDescGZIP(), []int{2}
}

func (x *FileChunk) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *FileChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileChunk) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

var File_proto_fileTransfer_proto protoreflect.FileDescriptor

const file_proto_fileTransfer_proto_rawDesc = "" +
	"\n" +
	"\x18proto/fileTransfer.proto\x12\ffiletransfer\"h\n" +
	"\rFolderRequest\x12\x1f\n" +
	"\vfolder_path\x18\x01 \x01(\tR\n" +
	"folderPath\x126\n" +
	"\bprogress\x18\x02 \x03(\v2\x1a.filetransfer.FileProgressR\bprogress\"C\n" +
	"\fFileProgress\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\"f\n" +
	"\tFileChunk\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x10\n" +
	"\x03eof\x18\x04 \x01(\bR\x03eof2_\n" +
	"\x13FileTransferService\x12H\n" +
	"\x0eDownloadFolder\x12\x1b.filetransfer.FolderRequest\x1a\x17.filetransfer.FileChunk0\x01B\tZ\a./protob\x06proto3"

var (
	file_proto_fileTransfer_proto_rawDescOnce sync.Once
	file_proto_fileTransfer_proto_rawDescData []byte
)

func file_proto_fileTransfer_proto_rawDescGZIP() []byte {
	file_proto_fileTransfer_proto_rawDescOnce.Do(func() {
		file_proto_fileTransfer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_fileTransfer_proto_rawDesc), len(file_proto_fileTransfer_proto_rawDesc)))
	})
	return file_proto_fileTransfer_proto_rawDescData
}

var file_proto_fileTransfer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_fileTransfer_proto_goTypes = []any{
	(*FolderRequest)(nil), // 0: filetransfer.FolderRequest
	(*FileProgress)(nil),  // 1: filetransfer.FileProgress
	(*FileChunk)(nil),     // 2: filetransfer.FileChunk
}
var file_proto_fileTransfer_proto_depIdxs = []int32{
	1, // 0: filetransfer.FolderRequest.progress:type_name -> filetransfer.FileProgress
	0, // 1: filetransfer.FileTransferService.DownloadFolder:input_type -> filetransfer.FolderRequest
	2, // 2: filetransfer.FileTransferService.DownloadFolder:output_type -> filetransfer.FileChunk
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_fileTransfer_proto_init() }
func file_proto_fileTransfer_proto_init() {
	if File_proto_fileTransfer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_fileTransfer_proto_rawDesc), len(file_proto_fileTransfer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_fileTransfer_proto_goTypes,
		DependencyIndexes: file_proto_fileTransfer_proto_depIdxs,
		MessageInfos:      file_proto_fileTransfer_proto_msgTypes,
	}.Build()
	File_proto_fileTransfer_proto = out.File
	file_proto_fileTransfer_proto_goTypes = nil
	file_proto_fileTransfer_proto_depIdxs = nil
}
